### ISSUE TITLE
Display dummy data

### ISSUE THREAD

**Issue by StefanFitoussi** [StefanFitoussi/Capstone-Project-Movie-Box#1]
## Value proposition

**As a** user,
**I want to** see a list of movies,
**so that** I can get inspiration what to watch next.

## Description
![Image](https://user-images.githubusercontent.com/113462689/201899398-d4ec6b41-c8a2-430f-8164-9e4e31749bd7.png)

## Acceptance criteria

 - [x] the app's title 'Movie-Box' is displayed in the header
 - [x] movies (dummy data) are displayed on the landing page, including the respective movie's title, release-date and runtime
 - [x] movies (dummy data) are displayed one below the other

## Tasks
- [x] create a landing page with the app's name inside the header
- [x] open a feature branch
- [x] display the app's title 'Movie-Box' in the header
- [x] create a dummy data movie list in a db.json, including the movie's title, release date and runtime
- [x] fetch the dummy movie-data from the db.json and display it on the landing page
- [x] create an unordered list for each movie with one list item for each movie's detail-type

## Complexity Estimation

M
