### ISSUE TITLE
Add movie fetch options

### ISSUE THREAD

**Issue by StefanFitoussi** [StefanFitoussi/Capstone-Project-Movie-Box#12]
## Value proposition

**As a** user,
**I want to** have different kinds of movie lists,
**so that** I can choose from different thematic options.

![Image](https://user-images.githubusercontent.com/113462689/205730705-e0acec52-8581-4c35-b693-5ae43c179b9e.png)

## Acceptance criteria

- [x] initially the start page displays the "popular" movie list
- [x] the start page displays a button for each type of movie list
- [ ] a click on one of these buttons shows 20 movies from the respective list
- [ ] a click on a different button displays 20 movies from corresponding movie list
- [ ] the different movie lists all share the same layout

## Tasks

- [x] open a feature branch
- [x] for each movie list add a button to the landing page
- [ ] write code to on-click-fetch the respective movie list from "TheMovieDB" and 
   render it on the landing page

## Complexity Estimation

L

**Comment by MeenaFoerderer** [comment]
Cool feature and nice US!

**Comment by StefanFitoussi** [comment]
Thanks! :)
