### ISSUE TITLE
Component Testing

### ISSUE THREAD

**Issue by StefanFitoussi** [StefanFitoussi/Capstone-Project-Movie-Box#13]
## Value proposition

**As a** developer,
**I want to** test components,
**so that** I can see if my app works correctly.

## Acceptance criteria

- [ ] the app has at least 2-3 component tests

## Tasks

- [ ] open a feature branch
- [ ] implement component tests

## Complexity Estimation

M
