### ISSUE TITLE
Display real data

### ISSUE THREAD

**Issue by StefanFitoussi** [StefanFitoussi/Capstone-Project-Movie-Box#2]
## Value proposition

**As a** user,
**I want to** see a list of real movies,
**so that** I can get inspiration what to watch next.

## Description
![Image](https://user-images.githubusercontent.com/113462689/201963434-1baf4770-664b-494d-aa50-efe9085cfcef.png)

Additionally the MovieCard should display the average user-rating, 
the release-date and the plot-overview.

## Acceptance criteria

- [x] the previous movie list is not displayed on the landing page
- [x] existing movies from the 'The Movie DB'-API are displayed on the landing page 
   with a separate card for each movie
- [x] the movies are fetched from 'The Movie DB'-"popular"-section
- [x] the number of displayed movies is 20
- [x] fetched movies are displayed on the landing page in no particular order
- [x] movies are displayed one below the other
- [x] each entry shows the movie's title and title-picture, the average user-rating, 
   the release-date and the plot-overview

## Tasks

- [x] open a feature branch
- [x] remove the dummy data from the landing page
- [x] create a MovieCard-Component and have it display a card for each movie, 
   containing the movie's title and title-picture, the average user-rating, the release-date, and the plot-overview
- [x] write a fetch function for the `The Movie DB´-API to fetch 20 movies from 
   the database's "popular"-section
- [x] use the existing unordered list to display the real movies

## Complexity Estimation

L

**Comment by FelineHuhn** [comment]
Hey Stefan, first I have to say: Gooood Job. :)
Now a question: In which order are the films sorted? If it's e.g. alphabetically sorted, you could add it to the AC's. 
And as I can see in userstory #1 you had dummy data for the unordered list until now. Maybe you could add to task: dummy data will be removed and the real movies will be displayed on the landing page instead

**Comment by StefanFitoussi** [comment]
Nice, thanks for the feedback! The movies are listed randomly. I will add this to the ACC's and add the dummy data task :)

**Comment by ahohnsen** [comment]
Hey Stefan,

Little reminder: The title of your user story should be the name of the feature, keep it short and descriptive. The title/name of the feature will also be the name for your branch. 🙂

**Comment by StefanFitoussi** [comment]
Thank you, I forgot about that. Will change it for my user stories :)

**Comment by EugenMoser** [comment]
looks very good for me

**Comment by StefanFitoussi** [comment]
Thanks! :)

**Comment by marialitwa** [comment]
Hej Stefan, looks good! I just see a tiny typo in description: overage => average :)

**Comment by StefanFitoussi** [comment]
Thanks, it's done! :)
