### ISSUE TITLE
Movie card details

### ISSUE THREAD

**Issue by StefanFitoussi** [StefanFitoussi/Capstone-Project-Movie-Box#3]
## Value proposition

**As a** user,
**I want to** see more details about each movie,
**so that** I can decide which one to watch.

![Image](https://user-images.githubusercontent.com/113462689/203086028-e0dfb9b4-7c69-401e-aacf-c1cb8ae5a0eb.png)

## Acceptance criteria

- [x] a click on the movie title image shows further movie details in the respective movie's card
- [x] the additional movie details are: title, user rating, release-date and plot summary

## Tasks

- [x] open a feature branch
- [x] add a function to the MovieCard-Component to show the respective movie's title, user rating, release date and plot summary on title picture click

## Complexity Estimation

M

**Comment by FelineHuhn** [comment]
Hey Stefan, i think the user-story title should include details because it's the main feature content of this story right? E.g. the title could be "movie details in separated card". 

And you have a typo in the whole doc, "sep**a**rate" is the right spelling :) another little typo is "decide" in the value proposition. And i would shorten the value proposition, maybe like "As a user, I want to see more details of each movie, so that I am able to make a better decision which movie I should watch".

Further more the wireframe doesn't show a card, but only text under the movie card. You should put a border around for visualize a card in the wireframe or maybe you should make two wireframes, to show how it should be displayed more understandable. Is the details button in the Movie card oder (like in the wireframe) next to the card on the left?

AC's: Maybe you should mentioned, that there is a "Details" button first, before you describe the button click maybe.

I love your App Idea 😍

**Comment by StefanFitoussi** [comment]
Thanks a lot for your feedback, Feline :)

**Comment by FelineHuhn** [comment]
Hey Stefan, 
in the markdown file is a second (and old) title, you should delete ist. 

i love your wireframes!

AC's: I think the first point is not part of this user story, but part of a story before... the Movie card should exist before you add the details button right? I think you can delete this point and add it to a story before maybe... I think the "second" click is not right, because it's an endless toggle... maybe you can describe this more clear. 

Tasks: Isn't the second point part of a user story before? And i think you should create a `MovieCard` Component, so you can render the Cards dynamic. Than it should read "add "Details" toggle-button to the `MovieCard` Component and than just like "write a function for toggling between show and hide movie details on button click" or something similar to it
