### ISSUE TITLE
Add watchlist function

### ISSUE THREAD

**Issue by StefanFitoussi** [StefanFitoussi/Capstone-Project-Movie-Box#7]
## Value proposition

**As a** user,
**I want to** save my favorite movies,
**so that** I can easily find them.

![Image](https://user-images.githubusercontent.com/113462689/204542315-fc05e40f-8e08-4e3c-9e33-d344c7684342.png)

## Acceptance criteria

- [x] each movie card has a "ADD"-button, which adds the respective movie on-click to the watchlist
- [x] added movies have a "REMOVE"-button which removes the respective movie on-click from the watchlist
- [x] added movies are displayed both on the watchlist and still on the initial list with all available movies (in this case with the "minus"-icon)

## Tasks

- [x] open a feature branch
- [x] add a "favorite"(ADD-REMOVE)-toggle icon to the MovieCard component and write a function to toggle add/remove the respective movie to/from the watchlist

## Complexity Estimation

M-L

**Comment by ahohnsen** [comment]
Hey Stefan,

I have a question for you:

What happens when I add a movie to the watchlist? Will it move to the watchlist or will it be still visible in the list with all available movies? If it will appear on both lists, it would be good to know if the "-" button will be visible also in both lists. I am just asking cause it is not clear from your wireframes and acceptance criteria.

Otherwise everything looks good 🚀

**Comment by StefanFitoussi** [comment]
Thank you for this question. The respective movie will still be visible in the list with all available movies with the "minus" displayed in the movie card. The movie will appear in both lists and both appearances will have a "minus"-icon.

I will add these aspacts to the usery story :)

**Comment by ahohnsen** [comment]
Cool :) I think that's a nice solution. So the user does not need to go to the watchlist to remove a movie from it :)
