### ISSUE TITLE
Add a watchlist

### ISSUE THREAD

**Issue by StefanFitoussi** [StefanFitoussi/Capstone-Project-Movie-Box#8]
## Value proposition

**As a** user,
**I want** a navigation option,
**so that** I can quickly switch to 
my watchlist and back.

![Image](https://user-images.githubusercontent.com/113462689/203793193-dfa34fc2-364f-468c-a8a8-98da2a8053fc.png)

## Acceptance criteria

- [x] a navbar with links for "home" and "watchlist" is displayed at the bottom of the screen
- [x] the button "home" has a house icon and navigates to the main movie list
- [x] the button "watchlist" has a bookmark icon and navigates to the watchlist
- [x] the watchlist is displayed on it's own page
- [x] the navbar is displayed on every page
- [x] no movies are displayed on the watchlist

## Tasks

- [x] open a feature branch
- [x] create a NavBar component and render the navbar at the bottom of the screen
- [x] add the navbar to the Layout component
- [x] add a WatchList component and render it on it's own page
- [x] add the followig router navigation functions to the navbar:
   - [x] to the landing page
   - [x] to the watchlist

## Complexity Estimation

M-L
